# Generated by Django 2.2.3 on 2021-01-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LisaMusica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cancion', models.CharField(max_length=50)),
                ('url_musica', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='imgMusica')),
            ],
            options={
                'verbose_name': 'LisaMusica',
                'verbose_name_plural': 'LisasMusicas',
            },
        ),
    ]
