# Generated by Django 2.2.3 on 2021-01-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReproductorDeMusicaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisamusica',
            name='categoria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lisamusica',
            name='nombre_cancion',
            field=models.CharField(max_length=100),
        ),
    ]
