# Generated by Django 2.2.3 on 2021-01-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReproductorDeMusicaApp', '0002_auto_20210130_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisamusica',
            name='genero',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
