# Generated by Django 2.2.3 on 2021-01-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReproductorDeMusicaApp', '0004_remove_lisamusica_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
    ]
