# Generated by Django 2.2.3 on 2021-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReproductorDeMusicaApp', '0005_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='lisamusica',
            name='genero',
            field=models.ManyToManyField(to='ReproductorDeMusicaApp.Genero'),
        ),
    ]
